### ISSUE TITLE
i found some issues

### ISSUE THREAD

**Issue by seema84** [NoChanceSD/PvPManager#103]
1# i cant translate the /pvplist output in the message config (not found)
2# is reversed ->

Other_Status_Enabled = &6[&8PvP&6] &6Spieler %p hat PvP ausgeschaltet!
Others_Status_Disabled = &6[&8PvP&6] &6Spieler %p hat PvP eingeschaltet!

right is ->

Other_Status_Enabled = &6[&8PvP&6] &6Spieler %p hat PvP eingeschaltet!
Others_Status_Disabled = &6[&8PvP&6] &6Spieler %p hat PvP ausgeschaltet!

3# i cant translate the /pvp name output (not found)
4# the pvp status do not change on a wg region with pvp flag
in a pvp arena the player can join with pvp false and the game dont work

**Comment by CloudeLecaw** [comment]
i know what u mean
its not in.
currently you need to "hardcode" the translation of this string ;)

But hardcoding is nothing for an owner of a server normaly.

so your right, the strings should be added.

**Comment by EvilOlaf** [comment]
This has been fixed already: https://github.com/NoChanceSD/PvPManager/commit/8a076dd7d4cb2ea9d899ab72b85789fa2033c872

**Comment by CloudeLecaw** [comment]
hm can be, i use my own langfile since a while :§
in my langfile this issues was fixed too ;)

**Comment by seema84** [comment]
ok problem 2 was fixed in the latest build but 1,3,4 still there

**Comment by CloudeLecaw** [comment]
create a new langfile :)

**Comment by seema84** [comment]
/pvplist has no line in the langfile and /pvp name dont work this its always english
a new langfile does not help

**Comment by seema84** [comment]
to 4#
if i join a arena (example battlearena) pvp is activ but player get the message pvp is disabled

**Comment by seema84** [comment]
[PvPManager] WorldGuard Found! Enabling WorldGuard Support
[22:00:57 ERROR]: Error occurred while enabling PvPManager v3.1.6 (Is it up to date?)
java.lang.ClassCastException: com.sk89q.worldguard.bukkit.WorldGuardPlugin cannot be cast to me.NoChance.PvPManager.Dependencies.Hooks.WorldGuard
at me.NoChance.PvPManager.Managers.PlayerHandler.<init>(PlayerHandler.java:33) ~[?:?]
at me.NoChance.PvPManager.PvPManager.onEnable(PvPManager.java:49) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by NoChanceSD** [comment]
I don't think you are using latest build.

**Comment by seema84** [comment]
i get it in #226 and #225

**Comment by NoChanceSD** [comment]
Paste the error with #226 please. I'm pretty sure that was fixed.

**Comment by seema84** [comment]
I'm pretty sure the error is still in 1.9.4 and #226

**Comment by NoChanceSD** [comment]
Ok, is it exactly the same error? Please paste it if not (or paste it anyway just in case)

**Comment by seema84** [comment]
ok its a other error

[PvPManager] Enabling PvPManager v3.1.6
[22:42:01 ERROR]: Error occurred while enabling PvPManager v3.1.6 (Is it up to date?)
java.lang.NullPointerException
at me.NoChance.PvPManager.Settings.Settings.initizalizeVariables(Settings.java:113) ~[?:?]
at me.NoChance.PvPManager.Managers.ConfigManager.initConfig(ConfigManager.java:89) ~[?:?]
at me.NoChance.PvPManager.Managers.ConfigManager.loadConfig(ConfigManager.java:65) ~[?:?]
at me.NoChance.PvPManager.Managers.ConfigManager.<init>(ConfigManager.java:36) ~[?:?]
at me.NoChance.PvPManager.PvPManager.loadFiles(PvPManager.java:69) ~[?:?]
at me.NoChance.PvPManager.PvPManager.onEnable(PvPManager.java:47) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Spigot-4af49dc-6d133d5]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-4af49dc-6d133d5]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-4af49dc-6d133d5]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361) [craftbukkit.jar:git-Spigot-4af49dc-6d133d5]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321) [craftbukkit.jar:git-Spigot-4af49dc-6d133d5]
at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [craftbukkit.jar:git-Spigot-4af49dc-6d133d5]
at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [craftbukkit.jar:git-Spigot-4af49dc-6d133d5]
at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [craftbukkit.jar:git-Spigot-4af49dc-6d133d5]
at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [craftbukkit.jar:git-Spigot-4af49dc-6d133d5]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [craftbukkit.jar:git-Spigot-4af49dc-6d133d5]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by NoChanceSD** [comment]
What is your config version? Did you use the premium version before and now using the free?

**Comment by seema84** [comment]
config version: 42 // no premium version befor
