### ISSUE TITLE
NPE on reload

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#111]
`/pm reload` throws me these.
Build 228 @ Spigot 1.8.8
```
[07:45:02] [Server thread/INFO]: PvPManager Reloaded!
[07:45:02] [Craft Scheduler Thread - 57/WARN]: Exception in thread "Craft Scheduler Thread - 57"
[07:45:02] [Craft Scheduler Thread - 58/WARN]: Exception in thread "Craft Scheduler Thread - 58"
[07:45:02] [Craft Scheduler Thread - 58/WARN]: org.apache.commons.lang.UnhandledException: Plugin PvPManager v3.1.8 generated an exception while executing task 103845
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Nodes must be provided.
        at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
        at me.NoChance.PvPManager.Managers.ConfigManager$2.run(ConfigManager.java:131)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

[07:45:02] [Craft Scheduler Thread - 50/WARN]: Exception in thread "Craft Scheduler Thread - 50"
[07:45:02] [Craft Scheduler Thread - 50/WARN]: org.apache.commons.lang.UnhandledException: Plugin PvPManager v3.1.8 generated an exception while executing task 103842
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Nodes must be provided.
        at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
        at me.NoChance.PvPManager.Managers.ConfigManager$2.run(ConfigManager.java:131)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

[07:45:02] [Craft Scheduler Thread - 57/WARN]: org.apache.commons.lang.UnhandledException: Plugin PvPManager v3.1.8 generated an exception while executing task 103843
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Nodes must be provided.
        at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
        at me.NoChance.PvPManager.Managers.ConfigManager$2.run(ConfigManager.java:131)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

[07:45:02] [Craft Scheduler Thread - 51/WARN]: Exception in thread "Craft Scheduler Thread - 51"
[07:45:02] [Craft Scheduler Thread - 51/WARN]: org.apache.commons.lang.UnhandledException: Plugin PvPManager v3.1.8 generated an exception while executing task 103844
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.yaml.snakeyaml.emitter.Emitter.expectNode(Emitter.java:400)
        at org.yaml.snakeyaml.emitter.Emitter.access$1600(Emitter.java:62)
        at org.yaml.snakeyaml.emitter.Emitter$ExpectBlockMappingSimpleValue.expect(Emitter.java:641)
        at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:216)
        at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:181)
        at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:205)
        at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
        at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
        at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:112)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
        at me.NoChance.PvPManager.Managers.ConfigManager$2.run(ConfigManager.java:131)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

```

**Comment by NoChanceSD** [comment]
Should get fixed by https://github.com/NoChanceSD/PvPManager/commit/ec0d2255987cb1f98ccaf7afbb951592f9b26beb
