### ISSUE TITLE
Error on disable

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#112]
```
[11:18:03] [Server thread/ERROR]: Error occurred while enabling PvPManager v3.1.8 (Is it up to date?)
java.lang.NullPointerException
        at me.NoChance.PvPManager.Settings.Messages.getString(Messages.java:107) ~[?:?]
        at me.NoChance.PvPManager.Settings.Messages.getMessages(Messages.java:140) ~[?:?]
        at me.NoChance.PvPManager.Settings.Messages.load(Messages.java:97) ~[?:?]
        at me.NoChance.PvPManager.Settings.Messages.setup(Messages.java:67) ~[?:?]
        at me.NoChance.PvPManager.PvPManager.loadFiles(PvPManager.java:70) ~[?:?]
        at me.NoChance.PvPManager.PvPManager.onEnable(PvPManager.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

```
[11:17:34] [Server thread/ERROR]: Error occurred while disabling PvPManager v3.1.8 (Is it up to date?)
java.lang.NullPointerException
        at me.NoChance.PvPManager.PvPlayer.getName(PvPlayer.java:51) ~[?:?]
        at me.NoChance.PvPManager.Player.TeamProfile.removeCombatTeam(TeamProfile.java:115) ~[?:?]
        at me.NoChance.PvPManager.PvPlayer.removeCombatTeam(PvPlayer.java:285) ~[?:?]
        at me.NoChance.PvPManager.Managers.PlayerHandler.handlePluginDisable(PlayerHandler.java:137) ~[?:?]
        at me.NoChance.PvPManager.PvPManager.onDisable(PvPManager.java:64) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:81) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:729) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

Build 228 @ (obviously) Spigot 1.8.8

**Comment by EvilOlaf** [comment]
Never mind. Seems like somehow the message file was messed up.
