### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [NoChanceSD/PvPManager#124]
logs
http://pastebin.com/WuFp71ca

timings
https://timings.aikar.co/v2/?id=a39d71271182431782fce5012b8ca972

**Comment by NoChanceSD** [comment]
Do you still have this error?

**Comment by mat41997** [comment]
i don't know : P

**Comment by EvilOlaf** [comment]
Confirmed.
```
[21:12:40] [Craft Scheduler Thread - 984/WARN]: Exception in thread "Craft Scheduler Thread - 984"
[21:12:40] [Craft Scheduler Thread - 984/WARN]: org.apache.commons.lang.UnhandledException: Plugin PvPManager v3.1.8 generated an exception while executing task 2131864
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Nodes must be provided.
        at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
        at me.NoChance.PvPManager.Managers.ConfigManager$2.run(ConfigManager.java:131)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

3.1.8 build 234

**Comment by NoChanceSD** [comment]
I never had this issue though, maybe some issue with users file.
