### ISSUE TITLE
[Free] PvPManager - Version Error for 1.12

### ISSUE THREAD

**Issue by fo11ow3r** [NoChanceSD/PvPManager#146]
Here's the server output for a Spigot 1.12 server:
[08:20:52 INFO]: [PvPManager] Enabling PvPManager v3.3.3.2
[08:20:52 ERROR]: Error occurred while enabling PvPManager v3.3.3.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at me.NoChance.PvPManager.Settings.Config.<init>(Config.java:36) ~[?:?]
	at me.NoChance.PvPManager.Managers.ConfigManager.initConfig(ConfigManager.java:89) ~[?:?]
	at me.NoChance.PvPManager.Managers.ConfigManager.loadConfig(ConfigManager.java:76) ~[?:?]
	at me.NoChance.PvPManager.Managers.ConfigManager.<init>(ConfigManager.java:37) ~[?:?]
	at me.NoChance.PvPManager.PvPManager.loadFiles(PvPManager.java:70) ~[?:?]
	at me.NoChance.PvPManager.PvPManager.onEnable(PvPManager.java:48) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by fo11ow3r** [comment]
@NoChanceSD  Thank you for updating! I appreciate your work on this plugin, and am glad to be able to use it on my small server!
