### ISSUE TITLE
Error On update

### ISSUE THREAD

**Issue by LordDWT** [NoChanceSD/PvPManager#156]
Error:
[06:54:34 INFO]: [PvPManager] Checking for updates...
[06:54:34 WARN]: Exception in thread "Thread-27"
[06:54:34 WARN]: java.lang.NullPointerException
[06:54:34 WARN]:        at java.io.StringReader.<init>(Unknown Source)
[06:54:34 WARN]:        at org.json.simple.JSONValue.parse(JSONValue.java:50)
[06:54:34 WARN]:        at me.NoChance.PvPManager.Libraries.Updater.BukkitUpdater.read(BukkitUpdater.java:158)
[06:54:34 WARN]:        at me.NoChance.PvPManager.Libraries.Updater.BukkitUpdater.runUpdater(BukkitUpdater.java:53)
[06:54:34 WARN]:        at me.NoChance.PvPManager.Libraries.Updater.Updater$1.run(Updater.java:35)
[06:54:34 INFO]: [PvPManager] No update found

Versions:
[09:06:30 INFO]: PvPManager version 3.3.3.2
[09:06:30 INFO]: Allows Administrators To Change Their PvP Mechanics.
[09:06:30 INFO]: Author: NoChanceSD

[09:06:59 INFO]: This server is running CraftBukkit version git-Spigot-4bd94dc-015bda4 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[09:06:59 INFO]: Checking version, please wait...
[09:07:00 INFO]: You are 1 version(s) behind

Plugins:
[09:07:29 INFO]: Plugins (31): CoreProtect, dynmap, WorldEdit, Essentials, Trading, LWC, Multiverse-Core, ProtocolLib, WorldGuard, NoCheatPlus, Shopkeepers, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, PermissionsEx, WGCustomFlags, Multiverse-Portals, EssentialsSpawn, GriefPrevention, PvPManager, BetterAlias, PvEManager, Orebfuscator4, AntiXRay, Dynmap-Essentials, AuthMe, Dynmap-WorldGuard, Magic, Multiverse-NetherPortals, JDynmapGriefPrevention, MobArena

**Comment by LordDWT** [comment]
This still happens.

**Comment by NoChanceSD** [comment]
Latest version doesn't seem to have this issue.
