### ISSUE TITLE
1.13.2 Paper, PvPManager breaks

### ISSUE THREAD

**Issue by FrozenBeard** [NoChanceSD/PvPManager#162]
This server is running Paper version git-Paper-409 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
PvPManager version 3.4 (latest dev)

```
[11:58:10] [Server thread/INFO]: [PvPManager] Enabling PvPManager v3.4*
[11:58:11] [Server thread/INFO]: [PvPManager] Vault Found! Using it for currency related features
[11:58:11] [Server thread/ERROR]: Error occurred while enabling PvPManager v3.4 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionContainer()Lcom/sk89q/worldguard/bukkit/RegionContainer;
	at me.NoChance.PvPManager.Dependencies.Hooks.WorldGuard.<init>(WorldGuard.java:21) ~[?:?]
	at me.NoChance.PvPManager.Managers.DependencyManager.checkForWorldguard(DependencyManager.java:60) ~[?:?]
	at me.NoChance.PvPManager.Managers.DependencyManager.<init>(DependencyManager.java:32) ~[?:?]
	at me.NoChance.PvPManager.PvPManager.onEnable(PvPManager.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.2.jar:git-Paper-409]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-409]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[patched_1.13.2.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.13.2.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-409]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[11:58:11] [Server thread/INFO]: [PvPManager] Disabling PvPManager v3.4
[11:58:11] [Server thread/ERROR]: Error occurred while disabling PvPManager v3.4 (Is it up to date?)
java.lang.NullPointerException: null
	at me.NoChance.PvPManager.PvPManager.onDisable(PvPManager.java:65) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.13.2.jar:git-Paper-409]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[patched_1.13.2.jar:git-Paper-409]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[patched_1.13.2.jar:git-Paper-409]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[patched_1.13.2.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.13.2.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-409]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by NoChanceSD** [comment]
Should be fixed in latest version.
