### ISSUE TITLE
Error is spammed in console  randomly

### ISSUE THREAD

**Issue by Towelie** [NoChanceSD/PvPManager#20]
[PvPManager] Task #17628579 for PvPManager v3.0-SNAPSHOT-b117 generated an exception
java.lang.NullPointerException
at me.NoChance.PvPManager.PvPlayer.getName(PvPlayer.java:43) ~[?:?]
at me.NoChance.PvPManager.Managers.PlayerHandler$1.run(PlayerHandler.java:111) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_survival.jar:git-Spigot-44c59bf-8f0f4ed]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_survival.jar:git-Spigot-44c59bf-8f0f4ed]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot_survival.jar:git-Spigot-44c59bf-8f0f4ed]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot_survival.jar:git-Spigot-44c59bf-8f0f4ed]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot_survival.jar:git-Spigot-44c59bf-8f0f4ed]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot_survival.jar:git-Spigot-44c59bf-8f0f4ed]

**Comment by Towelie** [comment]
Using latest spigotr (as of yesterday)

**Comment by NoChanceSD** [comment]
Thanks, latest build (118+) should fix this
