### ISSUE TITLE
java.lang.reflect.InvocationTargetException / Recount error?

### ISSUE THREAD

**Issue by TomLewis** [NoChanceSD/PvPManager#241]
I use this plugin https://www.spigotmc.org/resources/recount.3962/

Which, when someone is killed is throwing errors with PvPManager.
I cant tell if its Recount or PvPManager throwing the error.

Paper 1.12.2

3.13.4

```
[11:02:32] [Server thread/INFO]: [PVP Missive] Scurvy jnthnshldn tried to escape durin` combat!
[11:02:32] [Server thread/INFO]: ⚔ PvP AXE jnthnshldn was scuttled by joshini26's Iron Axe!
[11:02:32] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[11:02:32] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor156.invoke(Unknown Source)
[11:02:32] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:02:32] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[11:02:32] [Server thread/WARN]: 	at com.Zrips.Recount.CMILib.RawMessageManager.send(RawMessageManager.java:64)
[11:02:32] [Server thread/WARN]: 	at com.Zrips.Recount.CMILib.RawMessage.show(RawMessage.java:633)
[11:02:32] [Server thread/WARN]: 	at com.Zrips.Recount.CMILib.RawMessage.show(RawMessage.java:617)
[11:02:32] [Server thread/WARN]: 	at com.Zrips.Recount.Util.printTakenPlayerDamage(Util.java:375)
[11:02:32] [Server thread/WARN]: 	at com.Zrips.Recount.Util.PrintInfo(Util.java:241)
[11:02:32] [Server thread/WARN]: 	at com.Zrips.Recount.PlayerListener.onPlayerDeath(PlayerListener.java:479)
[11:02:32] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor125.execute(Unknown Source)
[11:02:32] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[11:02:32] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[11:02:32] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:02:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[11:02:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:422)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:463)
[11:02:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:106)
[11:02:32] [Server thread/WARN]: 	at me.NoChance.PvPManager.Managers.PlayerHandler.applyPunishments(PlayerHandler.java:136)
[11:02:32] [Server thread/WARN]: 	at me.NoChance.PvPManager.Listeners.PlayerListener.onPlayerLogout(PlayerListener.java:84)
[11:02:32] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor694.execute(Unknown Source)
[11:02:32] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[11:02:32] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[11:02:32] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:02:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:429)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1167)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:361)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[11:02:32] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[11:02:32] [Server thread/WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 149 path $[1].hoverEvent.value
[11:02:32] [Server thread/WARN]: 	at com.google.gson.internal.Streams.parse(Streams.java:60)
[11:02:32] [Server thread/WARN]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChatDeserializer.a(SourceFile:492)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChatDeserializer.a(SourceFile:517)
[11:02:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.IChatBaseComponent$ChatSerializer.a(SourceFile:212)
[11:02:32] [Server thread/WARN]: 	... 33 more
[11:02:32] [Server thread/WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 149 path $[1].hoverEvent.value
[11:02:32] [Server thread/WARN]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[11:02:32] [Server thread/WARN]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[11:02:32] [Server thread/WARN]: 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[11:02:32] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
[11:02:32] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
[11:02:32] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
[11:02:32] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
[11:02:32] [Server thread/WARN]: 	at com.google.gson.internal.Streams.parse(Streams.java:48)
[11:02:32] [Server thread/WARN]: 	... 37 more
[11:02:32] [Server thread/INFO]: Failed to show json message with packets, using command approach
[11:02:32] [Server thread/INFO]: Player '"jnthnshldn"' cannot be found
[11:02:32] [Server thread/INFO]: [Recount] Player joshini26 killed jnthnshldn in PirateCraft_1, -3024.34, 42.95, -1598.76
```

**Comment by TomLewis** [comment]
https://github.com/Zrips/CMI/issues/5110

**Comment by NoChanceSD** [comment]
The error seems to be from recount in this case.
