### ISSUE TITLE
Conflict with ChatControl

### ISSUE THREAD

**Issue by ebins** [NoChanceSD/PvPManager#31]
I get this error message only when using version 3.0 snapshot b118. 

[08:56:17 WARN]: Exception in thread "Craft Scheduler Thread - 0"
[08:56:17 WARN]: org.apache.commons.lang.UnhandledException: Plugin ChatControl
v5.1.2-BETA generated an exception while executing task 40
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at kangarko.chatcontrol.utils.UpdateCheck.run(UpdateCheck.java:49)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

Also causes conflict every time someone types something in chat.  I've verified that its only PvPManager that causes the exception, and only the latest version.

**Comment by NoChanceSD** [comment]
That seems to be an error of ChatControl, i don't see any relation to PvPManager there.

**Comment by ebins** [comment]
The conflict only occurs when using the latest version of PVPManager. I have not updated ChatControl in quite a while, and the issue did not start happening until last night when I updated to version b118. So, that's why It led me to believe it was this plugin, and not the chat manager... sorry, bit confused then...

**Comment by NoChanceSD** [comment]
Well, if it only happened when you updated it might be PvPManager somehow... but from that error i can't take any conclusion, try reporting to ChatControl to see if they can fix it.

**Comment by ebins** [comment]
Will do. Thanks. :)
