### ISSUE TITLE
The plugin d'ont load with error java in console.

### ISSUE THREAD

**Issue by tiradorus** [NoChanceSD/PvPManager#44]
[22:27:07] [INFO] [PvPManager] Enabling PvPManager v3.0-SNAPSHOT-b118
[22:27:07] [INFO] [PvPManager] Vault Found! Using it for currency related features
[22:27:07] [INFO] [PvPManager] WorldGuard Found! Enabling WorldGuard Support
[22:27:07] [INFO] [PvPManager] Factions Found! Hooked successfully
[22:27:07] [ERROR] Error occurred while enabling PvPManager v3.0-SNAPSHOT-b118 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.scoreboard.Scoreboard.getEntryTeam(Ljava/lang/String;)Lorg/bukkit/scoreboard/Team;
at me.NoChance.PvPManager.TeamProfile.(TeamProfile.java:22) ~[?:?]
at me.NoChance.PvPManager.PvPlayer.(PvPlayer.java:39) ~[?:?]
at me.NoChance.PvPManager.Managers.PlayerHandler.add(PlayerHandler.java:88) ~[?:?]
at me.NoChance.PvPManager.Managers.PlayerHandler.addOnlinePlayers(PlayerHandler.java:76) ~[?:?]
at me.NoChance.PvPManager.Managers.PlayerHandler.(PlayerHandler.java:33) ~[?:?]
at me.NoChance.PvPManager.PvPManager.onEnable(PvPManager.java:45) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[minecraft_server.jar:git-Spigot-870264a-0a645a2]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:286) [PlugMan.jar:?]
at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [minecraft_server.jar:git-Spigot-870264a-0a645a2]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

This is what is in my console, after the load of the plugin.

**Comment by EvilOlaf** [comment]
Make sure you run 1.8.7 of Spigot. It might not run well with versions below.

**Comment by tiradorus** [comment]
Yes, i Know what happened, i'm on pvp manager v 2.4.9 But it automaticaly update, i c'ant do anything, in config i use:
Update Check:
  Enabled: false
  Update Location: Spigot
  Auto Update: false

But, the Plugin automaticaly update, as i dont do anything.
I just c'ant rest in v2.4.9.

Français:
Ok j'ai compris ce qui se passe, j'ai la version 2.4.9 mais il se passe automatiquement en SnapShotB118. Je ne peux rien faire pour changer cela.
J'ai pourtant enlever l'auto Update dans la config avec:
Update Check:
  Enabled: false
  Update Location: Spigot
  Auto Update: false

Mais le plugin REPASSE automatiquement en dernière version , je ne peux rien faire.
Je n'ai à ma connaissance pas un seul moyen de le laisser en 2.4.9
Mais c'est vous l'expert ^^ je vous laisse faire.

**Comment by EvilOlaf** [comment]
Then there is probably something wrong with the updater ;D

**Comment by NoChanceSD** [comment]
Make sure to remove the jar file from the update folder.
