### ISSUE TITLE
JAUNT HAS EXPIRED!

### ISSUE THREAD

**Issue by FrozenBeard** [NoChanceSD/PvPManager#51]
[13:08:29] [Server thread/INFO]: [PvPManager] Checking for updates...
[13:08:29] [Thread-33/WARN]: JAUNT HAS EXPIRED! [http://jaunt-api.com]
[13:08:29] [Thread-33/WARN]: java.lang.NullPointerException
[13:08:29] [Thread-33/WARN]: at com.jaunt.UserAgent.e(SourceFile:2353)
[13:08:29] [Thread-33/WARN]: at com.jaunt.UserAgent.visit(SourceFile:940)
[13:08:29] [Thread-33/WARN]: at com.jaunt.UserAgent.visit(SourceFile:930)
[13:08:29] [Thread-33/WARN]: at me.NoChance.PvPManager.Updater.SpigotUpdater.runUpdater(SpigotUpdater.java:26)
[13:08:29] [Thread-33/WARN]: at me.NoChance.PvPManager.Updater.Updater$1.run(Updater.java:31)

**Comment by EvilOlaf** [comment]
Duplicate #47

**Comment by Arinerron** [comment]
@NoChanceSD How did you end up resolving this issue? I'm not working on this project, but in the project I am working on, I was also frustrated by it expiring.

**Comment by NoChanceSD** [comment]
@Arinerron I just stopped using jaunt. I had no idea it had an expiring time when i chose it.
Then found another library which is jsoup, it has worked well so far, no expire times at least. :)

**Comment by Arinerron** [comment]
@NoChanceSD Thank you for your response! It is too bad, Jaunt had some nice features. Hopefully jsoup has proxy and button-clicking support like Jaunt had.

They should really have a student discount or a personal use only version.
`</rant>` :stuck_out_tongue_winking_eye: 

Anyways, great job with this plugin, it looks like it's turning out very well! :)
