### ISSUE TITLE
Exception when trying to check for update

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#62]
Could be an issue of the dev build. Maybe interesting anways.

```
[09:36:30] [Thread-24/WARN]: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=503, URL=http://www.spigotmc.org/resources/pvpmanager.845/history
[09:36:30] [Thread-24/WARN]:    at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:537)
[09:36:30] [Thread-24/WARN]:    at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:493)
[09:36:30] [Thread-24/WARN]:    at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:205)
[09:36:30] [Thread-24/WARN]:    at org.jsoup.helper.HttpConnection.get(HttpConnection.java:194)
[09:36:30] [Thread-24/WARN]:    at me.NoChance.PvPManager.Updater.SpigotUpdater.runUpdater(SpigotUpdater.java:28)
[09:36:30] [Thread-24/WARN]:    at me.NoChance.PvPManager.Updater.Updater$1.run(Updater.java:31)
[09:36:30] [Server thread/INFO]: [PvPManager] No update found
```

Build 144

**Comment by NoChanceSD** [comment]
This is because of the ddos protection that spigot uses, not sure how to fix this. I guess only by changing the updater to Bukkit again.
