### ISSUE TITLE
NPE at startup

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#74]
```
[05:08:04] [Server thread/ERROR]: Error occurred while enabling PvPManager v3.0-SNAPSHOT-b163 (Is it up to date?)
java.lang.NullPointerException
        at me.NoChance.PvPManager.Config.Variables.initizalizeVariables(Variables.java:99) ~[?:?]
        at me.NoChance.PvPManager.Managers.ConfigManager.loadConfig(ConfigManager.java:40) ~[?:?]
        at me.NoChance.PvPManager.Managers.ConfigManager.<init>(ConfigManager.java:31) ~[?:?]
        at me.NoChance.PvPManager.PvPManager.loadFiles(PvPManager.java:61) ~[?:?]
        at me.NoChance.PvPManager.PvPManager.onEnable(PvPManager.java:36) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
``` 

Build 163

**Comment by NoChanceSD** [comment]
Thanks, there were to many changes in config so i will just rename it and create a new one automatically.
