### ISSUE TITLE
PlayerJoinEvent EventException

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#88]
Build 186
Could not test if some of the old issues have been solved. Just did a quick check of the logs.

```
[06:39:12] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to PvPManager v3.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassCastException: org.bukkit.configuration.MemorySection cannot be cast to java.util.Map
        at me.NoChance.PvPManager.Managers.ConfigManager.getUserData(ConfigManager.java:144) ~[?:?]
        at me.NoChance.PvPManager.Managers.PlayerHandler.addUser(PlayerHandler.java:92) ~[?:?]
        at me.NoChance.PvPManager.Managers.PlayerHandler.get(PlayerHandler.java:83) ~[?:?]
        at me.NoChance.PvPManager.Listeners.PlayerListener.onPlayerJoin(PlayerListener.java:181) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        ... 14 more
```

**Comment by NoChanceSD** [comment]
Should be fixed

**Comment by EvilOlaf** [comment]
Does this also solve an issue that players pvp status is always true at relog?

**Comment by NoChanceSD** [comment]
Yes, that should be fixed as well

**Comment by EvilOlaf** [comment]
Great! :+1:

**Comment by EvilOlaf** [comment]
Nope, seems not to be solved properly.

```
[09:30:11] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to PvPManager v3.0-SNAPSHOT-b190
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
        at me.NoChance.PvPManager.PvPlayer.loadData(PvPlayer.java:235) ~[?:?]
        at me.NoChance.PvPManager.Managers.PlayerHandler.addUser(PlayerHandler.java:92) ~[?:?]
        at me.NoChance.PvPManager.Managers.PlayerHandler.get(PlayerHandler.java:83) ~[?:?]
        at me.NoChance.PvPManager.Listeners.PlayerListener.onPlayerJoin(PlayerListener.java:181) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        ... 14 more
```

**Comment by NoChanceSD** [comment]
Is there any entry in users.yml with toogletime: 0 or something similar?
This is a different issue than the previous one btw.

**Comment by EvilOlaf** [comment]
Yes, there is one user with this value. Removed parts of the UUID for privacy concerns.

```
  xxxxxxxxxx-692c-4ed9-893f-xxxxxxxxxx:
    pvpstatus: false
    toggletime: 0
```
