### ISSUE TITLE
Event Exception

### ISSUE THREAD

**Issue by Sirse** [NoChanceSD/PvPManager#92]
Server - KCauldron version 1.7.10-1492.152 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

[09:36:00] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to PvPManager v3.0-SNAPSHOT-b190
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1492.152]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1492.152]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1492.152]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1492.152]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:1.7.10-1492.152]
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(Unknown Source) [mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:732) [nh.class:?]
	at modfixng.nms.packets.v1_7_R4.BlockDig.func_148833_a(BlockDig.java:45) [ModFixNG.jar:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) [ji.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NoSuchMethodError: org.bukkit.scoreboard.Team.removeEntry(Ljava/lang/String;)Z
	at me.NoChance.PvPManager.TeamProfile.restoreTeam(TeamProfile.java:89) ~[?:?]
	at me.NoChance.PvPManager.TeamProfile.setPvP(TeamProfile.java:100) ~[?:?]
	at me.NoChance.PvPManager.TeamProfile.setupTeams(TeamProfile.java:73) ~[?:?]
	at me.NoChance.PvPManager.TeamProfile.<init>(TeamProfile.java:23) ~[?:?]
	at me.NoChance.PvPManager.PvPlayer.<init>(PvPlayer.java:41) ~[?:?]
	at me.NoChance.PvPManager.Managers.PlayerHandler.get(PlayerHandler.java:83) ~[?:?]
	at me.NoChance.PvPManager.Listeners.PlayerListener.onPlayerInteract(PlayerListener.java:144) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1492.152]
	... 15 more

**Comment by NoChanceSD** [comment]
is there any message at server start such as

> Colored nametags disabled. Update your Spigot version.

**Comment by linkinkov** [comment]
same problem:
[01:51:06] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to PvPManager v3.0-SNAPSHOT-b190
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.28]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.28]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.28]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.28]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:102) [CraftEventFactory.class:1.7.10-1614.28]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:601) [CraftEventFactory.class:1.7.10-1614.28]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:469) [CraftEventFactory.class:1.7.10-1614.28]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:633) [CraftEventFactory.class:1.7.10-1614.28]
	at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1379) [sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(EntityPlayer.java:1240) [yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:901) [sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1153) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:652) [mw.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1399) [yz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1558) [nh.class:?]
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1004) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:822) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.IllegalAccessError: tried to access method com.earth2me.essentials.Essentials.getUser(Lorg/bukkit/entity/Player;)Lcom/earth2me/essentials/User; from class me.NoChance.PvPManager.Listeners.EntityListener
	at me.NoChance.PvPManager.Listeners.EntityListener.onDamageActions(EntityListener.java:141) ~[?:?]
	at me.NoChance.PvPManager.Listeners.EntityListener.onPlayerDamageMonitor(EntityListener.java:102) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.28]
	... 23 more
